name: Build and publish nuget packages

on:
  push:
    branches:
    - master

  #release:
  #  types: [published]
    
env:
    NUGET_API_KEY: ${{secrets.NUGET_API_KEY}}

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x

    - name: Use Fun.Build
      run: dotnet fsi ./build.fsx
